apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    app: nginx-gateway
    component: gateway
spec:
  selector:
    app: nginx-gateway
  ports:
    - name: metrics
      port: 9113
      targetPort: metrics
