apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - nginx-gateway
  selector:
    matchLabels:
      component: gateway
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
